name: Build & Test

on: [pull_request, workflow_dispatch]

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  build
    runs-on: ubuntu-latest
    if: ${{ github.triggering_actor != 'github-classroom[bot]' }}
    timeout-minutes: 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: corretto

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12.1
          cache-read-only: false

      - name: Test LinkedList
        run: ./gradlew :testList

      - name: Test HashMap
        run: ./gradlew :testHashMap

      - name: Test AvlTree
        run: ./gradlew :testAvlMap